# Shared configuration for ALL services
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.darum.ng: INFO
    org.springframework.cloud.gateway: DEBUG

spring:
  cloud:
    config:
      override-none: true
