server:
  port: 8082

# ADD THIS
eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
  client:
    initial-instance-info-replication-interval-seconds: 30

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: user
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true      # ← Move this up one level
    fetch-registry: true            # ← Move this up one level
